# Generated by Django 4.0.6 on 2022-07-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=1, upload_to='projects', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
